### PR TITLE
OSOE-589: Shape Tracing should skip the PageTitle shape

### LINKED ISSUE #120: Shape Tracing should skip the PageTitle shape (OSOE-589)
This is the shape that goes into the `<title>` HTML element. As far as I've seen the inner HTML of the `<title>` element is treated as plain text in every current browser, so the `<!-- .... -->` is rendered into the beginning of the window title.

image

The shape tracing should make an exception by skipping PageTitle shape for a better developer experience and easier UI testing setup.

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-589)

### PR DESCRIPTION
**Pull request by DemeSzabolcs**
[OSOE-589](https://lombiq.atlassian.net/browse/OSOE-589)
Fixes #120

[OSOE-589]: https://lombiq.atlassian.net/browse/OSOE-589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: Lombiq.HelpfulExtensions/Extensions/ShapeTracing/ShapeTracingShapeEvents.cs [hunk 1]
```diff
@@ -22,6 +22,15 @@ public Task DisplayedAsync(ShapeDisplayContext context)
         var builder = new HtmlContentBuilder(6);
         var shapeMetadata = context.Shape.Metadata;
 
+        var isPageTitle = shapeMetadata.Type == "PageTitle";
```
Comment (sarahelsaig) [inline Lombiq.HelpfulExtensions/Extensions/ShapeTracing/ShapeTracingShapeEvents.cs]: Replace the hard coded string with `nameof(PageTitleShapes.PageTitle)` (in namespace `OrchardCore.DisplayManagement.Shapes`). It's not likely that the name will even change, but I've seen more egregious breaking changes from OC, so it helps to have a warning.

File: Lombiq.HelpfulExtensions/Extensions/ShapeTracing/ShapeTracingShapeEvents.cs [hunk 2]
```diff
@@ -22,6 +22,15 @@ public Task DisplayedAsync(ShapeDisplayContext context)
...
+
+        // This is needed to have the shape info as a comment, otherwise it would be put in the title.
+        if (isPageTitle)
+        {
+            builder.AppendHtml(context.ChildContent);
+            builder.AppendHtmlLine("</title>");
```
Comment (sarahelsaig) [inline Lombiq.HelpfulExtensions/Extensions/ShapeTracing/ShapeTracingShapeEvents.cs]: This leaves the original closing tag dangling, which is invalid:
image

Also it's totally valid to use the `PageTitle` shape in the main document or anywhere else outside of the header's `<title>` element. In that case this closing element will fail the HTML validation.

**Review by sarahelsaig — CHANGES_REQUESTED** [review]

File: Lombiq.HelpfulExtensions/Extensions/ShapeTracing/ShapeTracingShapeEvents.cs [hunk 3]
```diff
@@ -75,15 +76,29 @@ void AddIfNotNullOrEmpty(string name, string value)
...
+        // This is needed to have the shape info as a comment, otherwise it would be put in the title.
+        if (isPageTitle)
+        {
+            var log = string.Empty;
+
+            using (var writer = new System.IO.StringWriter())
+            {
+                builderShapeInfo.WriteTo(writer, HtmlEncoder.Default);
+                log = writer.ToString();
+            }
```
Comment (sarahelsaig) [inline Lombiq.HelpfulExtensions/Extensions/ShapeTracing/ShapeTracingShapeEvents.cs]: We [already have](https://github.com/Lombiq/Helpful-Libraries/blob/04d0ca2f694d65b15c8c105bc0dbc87527b0737d/Lombiq.HelpfulLibraries.AspNetCore/Localization/LocalizedHtmlStringExtensions.cs#L26) an extension method for this in HL.
So it can be simplified to `var log = builderShapeInfo.Html();`
(or even skip the temporary variable and use the `builderShapeInfo.Html()` directly)

File: Lombiq.HelpfulExtensions/Extensions/ShapeTracing/ShapeTracingShapeEvents.cs [hunk 4]
```diff
@@ -75,15 +76,29 @@ void AddIfNotNullOrEmpty(string name, string value)
...
+
+            _logger.LogInformation("PageTitle Shape information:\n{ShapeInformation}", log);
```
Comment (sarahelsaig) [inline Lombiq.HelpfulExtensions/Extensions/ShapeTracing/ShapeTracingShapeEvents.cs]: I'd prefer if we always logged, not just for PageTitle.

**Review by sarahelsaig — CHANGES_REQUESTED** [review]
