### PR TITLE
OSOE-576: Fixing target-blank.js

### LINKED ISSUE #116: Fix issues in target-blank.js (OSOE-576)
Follow-up to https://github.com/Lombiq/Helpful-Extensions/issues/104.

See comments [here](https://github.com/Lombiq/Helpful-Extensions/pull/114#pullrequestreview-1305260226) and below.

1. Use [`DOMContentLoaded`](https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event) event instead of `load`. There's no third parameter there.
2. Remove the `setTimeout` indirection from the event handler. Simply pass `targetBlank` as the handler.
3. Remove superfluous configuration from package.json file:
   a. `"nodejsExtensions"`
   b. `"devDependencies"`
4. Use compiled scripts from _wwwroot\js_ folder instead of _wwwroot\scripts_ [here](https://github.com/Lombiq/Helpful-Extensions/blob/dev/Lombiq.HelpfulExtensions/ResourceManagementOptionsConfiguration.cs#L15) after 3.a.
5. Reorder the conditions [here](https://github.com/Lombiq/Helpful-Extensions/blob/dev/Lombiq.HelpfulExtensions/Assets/Scripts/target-blank.js#L7-L9).

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-576)

### PR DESCRIPTION
**Pull request by TheHydes**
[OSOE-576](https://lombiq.atlassian.net/browse/OSOE-576)

Fixes #116

[OSOE-576]: https://lombiq.atlassian.net/browse/OSOE-576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

File: Lombiq.HelpfulExtensions/ResourceManagementOptionsConfiguration.cs [hunk 1]
```diff
@@ -12,7 +12,7 @@ public class ResourceManagementOptionsConfiguration : IConfigureOptions<Resource
     static ResourceManagementOptionsConfiguration() =>
         _manifest
             .DefineScript(TargetBlank)
-            .SetUrl(WwwRoot + "scripts/target-blank.min.js", WwwRoot + "scripts/target-blank.js")
+            .SetUrl(WwwRoot + "js/target-blank.min.js", WwwRoot + "js/target-blank.js")
```
Comment (0liver) [inline Lombiq.HelpfulExtensions/ResourceManagementOptionsConfiguration.cs]: I would argue that as long as we don't need, or expect to need in the near future, to reuse the `WwwRoot` path, prefer one that removes even more duplication, e.g.:
```suggestion
            .SetUrl(ScriptRoot + "target-blank.min.js", ScriptRoot + "target-blank.js")
```
Replace `Wwwroot` with `ScriptRoot`, and add the `js/` part to it.

File: Lombiq.HelpfulExtensions/Assets/Scripts/target-blank.js [hunk 2]
```diff
@@ -5,16 +5,11 @@
 
         for (let i = 0; i < links.length; i++) {
             if (!links[i].href.match(/^mailto:/) &&
-                (links[i].hostname !== currentHostname &&
-                (!links[i].href.match(/^javascript:/i)))) {
+                links[i].hostname !== currentHostname &&
+                !links[i].href.match(/^javascript:/i)) {
```
Comment (0liver) [inline Lombiq.HelpfulExtensions/Assets/Scripts/target-blank.js]: These checks can be ordered and simplified, discarding the regex usage and simplifying the whole expression as follows:

```c#
            if (links[i].hostname !== currentHostname &&
                !links[i].href.startsWith('javascript:') &&
                !links[i].href.startsWith('mailto:')) {
```

File: Lombiq.HelpfulExtensions/Assets/Scripts/target-blank.js [hunk 3]
```diff
@@ -5,16 +5,11 @@
...
             }
         }
     }
-    window.addEventListener(
-        'load',
-        () => {
-            window.setTimeout(targetBlank, 100);
-        },
-        false);
+    document.addEventListener('DOMContentLoaded', targetBlank);
```
Comment (0liver) [inline Lombiq.HelpfulExtensions/Assets/Scripts/target-blank.js]: Let's also rename the function to something more explicit like `addTargetBlank`.

**Review by 0liver — CHANGES_REQUESTED** [review]

File: Lombiq.HelpfulExtensions/Assets/Scripts/target-blank.js (hunk 2 above)
Comment (TheHydes) [reply Lombiq.HelpfulExtensions/Assets/Scripts/target-blank.js]: Analyzer error: Script URL is a form of eval. At line 8: !links[i].href.startsWith('javascript:') &&

Comment (0liver) [reply Lombiq.HelpfulExtensions/Assets/Scripts/target-blank.js]: Please link the error in the log. Didn't you get that error locally?

Comment (TheHydes) [reply Lombiq.HelpfulExtensions/Assets/Scripts/target-blank.js]: https://github.com/Lombiq/Open-Source-Orchard-Core-Extensions/actions/runs/4232004950

image

Locally there are no problems/errors, only GHA throws this.

@0liver

Comment (TheHydes) [reply Lombiq.HelpfulExtensions/Assets/Scripts/target-blank.js]: This error did come up earlier, when working on OSOE-476, thats why i changed the script to its current form, meaning this:
links[i].hostname !== currentHostname &&
                !links[i].href.match(/^javascript:/i)) {

Comment (TheHydes) [reply Lombiq.HelpfulExtensions/Assets/Scripts/target-blank.js]: This would be a working solution, with the requested reordering:
image

If you accept it.

Comment (0liver) [reply Lombiq.HelpfulExtensions/Assets/Scripts/target-blank.js]: FYI, you can link to individual lines in the log like this:

image

1. I'm surprised you don't see any errors locally because you should.
2. Tricking the analyzer is definitely **_not_** the desired way to resolve the warning.

Instead, disable the warning for this concrete use case **because it refers to code that is not our own**. The [no-script-url](https://eslint.org/docs/latest/rules/no-script-url) rule triggers to prevent the usage of `javascript:` URLs. In the current script, we are not using them - the script is meant to run on 3rd-party pages that we may not control. This is a case where suppressing the warning and adding an explanatory comment to the suppression is the correct approach.

You'll find documentation on how exactly to suppress linter warnings in the NE docs.

File: Lombiq.HelpfulExtensions/Assets/Scripts/target-blank.js [hunk 4]
```diff
@@ -1,20 +1,16 @@
...
+    function addTargetBlank() {
         const links = document.querySelectorAll('a');
         const currentHostname = window.location.hostname;
 
         for (let i = 0; i < links.length; i++) {
-            if (!links[i].href.match(/^mailto:/) &&
-                (links[i].hostname !== currentHostname &&
-                (!links[i].href.match(/^javascript:/i)))) {
+            if (links[i].hostname !== currentHostname &&
+                // eslint-disable-next-line no-script-url
```
Comment (0liver) [inline Lombiq.HelpfulExtensions/Assets/Scripts/target-blank.js:10]: Please follow refer to the last paragraph of https://github.com/Lombiq/NodeJs-Extensions/blob/dev/Lombiq.NodeJs.Extensions/Docs/JavaScript.md#eslint-rules.

Add the comment above the existing one.

**Review by 0liver — CHANGES_REQUESTED** [review]

**Review by 0liver — APPROVED** [review]
